version: "3.8"

services:
  flighttracepro:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: flighttracepro-dev
    ports:
      - "8000:8000"
    environment:
      - LIVE_POST_KEY=${LIVE_POST_KEY:-}
      - CESIUM_ION_TOKEN=${CESIUM_ION_TOKEN:-}
    # Hot-reload and live-edit server/static during development
    # Appends to Dockerfile ENTRYPOINT (uvicorn app:app ...)
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app", "--reload-dir", "/app/static", "--reload-delay", "0.25"]
    volumes:
      - ./server/app.py:/app/app.py:rw
      - ./server/gpx_to_kml.py:/app/gpx_to_kml.py:rw
      - ./static:/app/static:ro
    env_file:
      - .env
