name: Release FlightTracePro (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'client/**'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: ver
        shell: bash
        run: |
          VER=$(cat client/VERSION | tr -d '\r\n')
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r client/requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller --clean client\FlightTracePro.spec

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: flighttracepro-v${{ env.VERSION }}-${{ github.run_number }}
          name: FlightTracePro v${{ env.VERSION }} (build ${{ github.run_number }})
          draft: false
          prerelease: false
          files: |
            dist/FlightTracePro.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
