name: Release FlightTracePro (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'client/**'

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: ver
        shell: bash
        run: |
          VER=$(cat client/VERSION | tr -d '\r\n')
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r client/requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller --clean --noconsole --onefile --name FlightTracePro ^
            --hidden-import SimConnect ^
            --collect-all SimConnect ^
            --collect-submodules websockets ^
            --collect-submodules requests ^
            --collect-data certifi ^
            client\msfs_bridge_gui.pyw --specpath client

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: flighttracepro-v${{ env.VERSION }}-${{ github.run_number }}
          release_name: FlightTracePro v${{ env.VERSION }} (build ${{ github.run_number }})
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/FlightTracePro.exe
          asset_name: FlightTracePro.exe
          asset_content_type: application/octet-stream
